const constants = {
    CHANGE_CURRENCY: 'CHANGE_CURRENCY',
    FETCH_24H_TICKER: 'FETCH_24H_TICKER',
    UPDATE_CURRENCIES_DATA: 'UPDATE_CURRENCIES_DATA',
    UPDATE_CURRENCY_DATA: 'UPDATE_CURRENCY_DATA',
    STOP_FETCH_24H_TICKER: 'STOP_FETCH_24H_TICKER',
    SET_LOADING: 'SET_LOADING',
    STOP_LOADING: 'STOP_LOADING'
}
export default constants